name: Waka Readme

on:
  schedule:
    # Runs at 12am IST every day
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Avimanyu Ghimire
          COMMIT_AUTHOR_EMAIL: aevy.gh@gmail.com
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          SHOW_LINES_OF_CODE: false
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE: true
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_UPDATED_DATE: false
          SHOW_TOTAL_CODE_TIME: true
          SHOW_TITLE: false